language: php
sudo: required
dist: trusty
php:
 - '5.6'
 - '7.1'
install:
 - php -r 'copy("http://lens.guide/lens.phar", "lens"); chmod("lens", 0755);'
 - composer install
script:
 - ./lens --report=xunit
notifications:
   email:
      on_success: never
      on_failure: always
